### PR TITLE
add `LightClientHeader` wrapper

### PR DESCRIPTION
**Pull request by etan-status**
The light client data structures were changed to accommodate additional fields in future forks (e.g., to also hold execution data).

There is a minor change to the JSON serialization, where the `header` properties are now nested inside a `LightClientHeader`. The SSZ serialization remains compatible.

See https://github.com/ethereum/consensus-specs/pull/3190

### CODE REVIEW

**Comment by etan-status** [comment]
(This one should only be merged if https://github.com/ethereum/consensus-specs/pull/3190 gets accepted).

**Review by rolfyone — APPROVED** [review]
Lgtm

**Comment by rolfyone** [comment]
ick i didnt follow my own suggestion and ask for this to be added to change log :/

**Comment by etan-status** [comment]
Already is listed, the change is for an API that was not yet part of a release.

In CHANGES.md, I noticed just now though that they incorrectly refer to `/eth/v2/beacon`, while in realitiy these endpoints are all at `v1`.

**Comment by rolfyone** [comment]
ah ok, that'll be my fault, i did a huge batch to get changes started

**Pull request merged**
