### PR TITLE
Use ERC-55 mixed-case checksum address encoding for execution address

### PR DESCRIPTION
**Pull request by nflaig**
Based on discussion in https://github.com/ethereum/beacon-APIs/pull/395 it would be good if we could use  [ERC-55 mixed-case checksum address encoding](https://github.com/ethereum/ercs/blob/master/ERCS/erc-55.md) for execution addresses in beacon API spec.

If this gets merged we should also do the same to keymanager API spec ([types/eth_address.yaml#L2](https://github.com/ethereum/keymanager-APIs/blob/a8c45a15cf820a1a832eafaec1c64ea31ed6f2ca/types/eth_address.yaml#L2)). Builder API spec references [SignedValidatorRegistration](https://github.com/ethereum/builder-specs/blob/22a17d312bdd18aba59aaa536002553759a55c16/builder-oapi.yaml#L78-L79) from beacon API spec so we should be fine there (some example values could be updated)

### CODE REVIEW

**Comment by Karlitos88** [comment]
TheNewFactory@Art&Contents.Red 
nflaig:eip-55-execution-address
Realizar verificación automática revisión de aprobación 
Gracias por su labor

**Comment by Karlitos88** [comment]
JUANCARLOSS1977 
Gracias todos los participantes que hacéis todo más facil

**Comment by Karlitos88** [comment]
Https://github blog/chamgelog/2023-06-13-github actions -will-run-on-of-node16-instread-of-node12-by-default/ 
JuancarlosS1977 necesario cambiar nodo12 × nodo16
Obtener revisiones antes sustraer 
TheNewFactory@Art&Contents.Red-18-12-2023

**Review by philknows — APPROVED** [review]

**Review by dapplion — DISMISSED** [review]

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
