### PR TITLE
added changes markdown

### PR DESCRIPTION
**Pull request by rolfyone**
Having a look at if we can maintain a changes list, with the hope that we might be able to see what's been changed and maybe help clients find where they're up to...

### CODE REVIEW

**Comment by rkapka** [comment]
I love this idea. I am updating Prysm as we speak because I missed several merged PRs...

**Comment by dapplion** [comment]
Yes that would be great info for downstream consumers

**Comment by rolfyone** [comment]
Ok cool, lets see how we go keeping it up to date I guess :)

**Review by michaelsproul — APPROVED** [review]
LGTM!

I'll try to fill in the Lighthouse column at some point

**Pull request merged**
