### PR TITLE
Add peers v2 without meta

### PR DESCRIPTION
**Pull request by dapplion**
- Suggested in https://github.com/ethereum/beacon-APIs/issues/366

Any consumer can derive the number of items by just doing `len(data)`. Creating a new route as a property is deleted from the response object

Closes https://github.com/ethereum/beacon-APIs/issues/366

### CODE REVIEW

**Review by rolfyone — COMMENTED** [review]
we can probably deprecate the v1 peers if we do add this, and should add to changes list :)

**Comment by arnetheduck** [comment]
This feels like a lot of bother for a small aesthetic nuisance in a fringe interface..

**Comment by dapplion** [comment]
> This feels like a lot of bother for a small aesthetic nuisance in a fringe interface..

Also true, taking the counter argument there's really no harm in sticking with this oddity that already handled by all implementations.

**Comment by nflaig** [comment]
It is an outlier and hence needs some special handling during parsing if you implement a generic http client/server. It's a minor thing but probably not wrong to get rid of technical debt.

**Comment by rolfyone** [comment]
Sounds like maybe we close the issue as 'won't fix'?

**Pull request closed without merging**
