### PR TITLE
Registrations for exited or unknown validators will not be sent to the builder network

### PR DESCRIPTION
**Pull request by StefanBratanov**
Clarify in the `registerValidator` description that registrations for `exited` or unknown validators will not be sent to the builder network.

Related to https://github.com/flashbots/mev-boost/issues/245

### CODE REVIEW

**Comment by ralexstokes** [comment]
noting that the builder specs only accept `active` or `pending` validators: https://github.com/ethereum/builder-specs/blob/main/apis/builder/validators.yaml#L7

it would make sense to ensure alignment on this so the beacon node/validator client don't end up doing extra work they don't need to do

**Comment by StefanBratanov** [comment]
> noting that the builder specs only accept `active` or `pending` validators: https://github.com/ethereum/builder-specs/blob/main/apis/builder/validators.yaml#L7
> 
> it would make sense to ensure alignment on this so the beacon node/validator client don't end up doing extra work they don't need to do

Thank you. Makes sense. Changed the description.

**Review by michaelsproul — DISMISSED** [review]

**Comment by rolfyone** [comment]
one minor comment from @mcdee re. wording, which we can fix easily before merging:
```
I'm not a massive fan of the use of "will" in the text.  If this is a specification they should be "must" (if I'm reading the spec correctly).
```

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
