### PR TITLE
Add blob_sidecar event

### PR DESCRIPTION
**Pull request by dapplion**
- Adds blob_sidecar event to SSE, see https://github.com/ethereum/beacon-APIs/issues/348 for rationale

**Discussion points**

- unsure to name the event `blob` or `blob_sidecar`. There won't be two different types of blob events so `blob` is shorter. But `blob_sidecar` matches the returned container summary.
- should the event include the kzg_commitment, the versioned hash or both? I tend to say that the version_hash is more useful since that's what the app layer is concerned about. Also one can derive the version hash, see [`kzg_commitment_to_versioned_hash`](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md#kzg_commitment_to_versioned_hash)

Closes https://github.com/ethereum/beacon-APIs/issues/348

### CODE REVIEW

**Comment by mcdee** [comment]
Rationale behind including the KZG commitment is that https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md#beaconblockbody only contains the commitment.  So if (for example) you received a `blob` event but wanted to see if the same blob had shown up in an earlier (orphaned) block you could do so relatively simply.

Not sure about how useful this would be in the real world, but the commitment is the only way that I can see to link blobs to consensus blocks (beyond the obvious other information already in the event).

I would include the versioned hash as well, as that provides a similar function for the execution layer.

**Comment by james-prysm** [comment]
> blob_sidecar matches the returned container summary.
casting my vote for blob_sidecar

**Review by rkapka — DISMISSED** [review]
looks good to me

**Review by rolfyone — DISMISSED** [review]
LGTM, just needs to be added to the change list.

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
