### PR TITLE
chore: pin redocli version

### PR DESCRIPTION
**Pull request by mpetrunic**
cc @rolfyone

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM, does look like a bug in the linter, so this is a reasonable measure.

**Comment by jimmygchen** [comment]
Hi @rolfyone @mpetrunic do you recall the reason for pinning the version and what the linter bug was? We're introducing the same linter to [builder-specs](https://github.com/ethereum/builder-specs), so it'd be useful to keep track of this so we know when to upgrade. Thanks!

**Comment by mpetrunic** [comment]
> Hi @rolfyone @mpetrunic do you recall the reason for pinning the version and what the linter bug was? We're introducing the same linter to [builder-specs](https://github.com/ethereum/builder-specs), so it'd be useful to keep track of this so we know when to upgrade. Thanks!

https://github.com/ethereum/beacon-APIs/actions/runs/3523507907/jobs/5907749543

This should work since type field was present in reference object

**Comment by jimmygchen** [comment]
Ahh that one, I've been getting that error locally all the time.  Thank you for the quick response!

**Pull request merged**
