### PR TITLE
Give liveness epoch same "shape" as attester duties

### PR DESCRIPTION
**Pull request by arnetheduck**
https://github.com/ethereum/beacon-APIs/pull/131 introduced a new liveness endpoint - the request is similar to attester duties in that we query a list of validators for data pertaining to a particular epoch - as such, it seems reasonable to keep the two requests similar in terms of their URL/postdata structure.

### CODE REVIEW

**Comment by arnetheduck** [comment]
cc @paulhauner

**Comment by rolfyone** [comment]
my understanding was that it's not really something we can query for anything but current or previous epoch... it seems that the epoch field is just going to result in false unless it's very carefully used...

**Comment by arnetheduck** [comment]
> it's not really something we can query for anything but current or previous epoch

it's allowed, just not required - the data _could_ be synthesized from a state for example, or if a client wants to implement "deep" doppelganger protection (ie more than 2 epochs of silence)

**Comment by rolfyone** [comment]
to me this makes sense overall, just would like to hear from @paulhauner and potentially @mehdi-aouadi to get opinions of people implementing...

**Comment by dapplion** [comment]
Change looks good to me :+1:

**Review by paulhauner — APPROVED** [review]
LGTM!

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
