### PR TITLE
fix: allow query config override

### LINKED ISSUE #255: `dev` bookmark does not direct to `dev` spec
I bookmarked https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev, but whenever I open the bookmark I see `v2.3.0` in the 'Select a definition' dropdown, and looking at the endpoints they are indeed from v2.3.0. Can this be fixed?

### PR DESCRIPTION
**Pull request by mpetrunic**
resolves #255

### CODE REVIEW

**Comment by mpetrunic** [comment]
cc @rkapka

**Review by rkapka — APPROVED** [review]

**Review by rolfyone — COMMENTED** [review]
looks good to me, but I'm not sure how to test it short of merging :)

**Review by rolfyone — APPROVED** [review]

**Comment by rolfyone** [comment]
It doesn't look like I can get the dev version still, the dev version is missing recent changes...

**Comment by mpetrunic** [comment]
> It doesn't look like I can get the dev version still, the dev version is missing recent changes...

If I click link in issue now, it opens dev schema. Does it not work for you?

**Comment by rolfyone** [comment]
actually, it does have bls_to_execution in the events, so it must be... ok all good...

**Pull request merged**
